### ISSUE TITLE
ModuleNotFoundError: No module named 'embreex'

### ISSUE THREAD

**Issue by kobeshegu** [wenquanlu/HandRefiner#10]
Hi quanlu,
I installed trimesh following your instructions, but fail to launch the code due to: "ModuleNotFoundError: No module named 'embreex'", is there any way to fix this?
Thanks.

**Comment by wenquanlu** [comment]
Hi, maybe try pip install embreex?
or pip install trimesh[easy] ?

**Comment by kobeshegu** [comment]
> Hi, maybe try pip install embreex? or pip install trimesh[easy] ?

It turns out the ubuntu system is too old for me to install the embreex, I fixed this by upgrading the system, thanks.
