### ISSUE TITLE
The quality of the generated images has decreased

### ISSUE THREAD

**Issue by YouTianlong** [wenquanlu/HandRefiner#15]
Hi,I found that some texture details are missing from the original image in the generated image.
The generated image should remain unchanged except for the hand area, right?

![input](https://github.com/wenquanlu/HandRefiner/assets/11797662/11bacd4d-6583-4a68-bab8-bff03a63f128)
![output](https://github.com/wenquanlu/HandRefiner/assets/11797662/82705dc5-e95a-49a5-b6ed-2f87dfec349c)

Comparing the two pictures, it is obvious that the girl has a problem with her eyes.
Thanks.

**Comment by wenquanlu** [comment]
Hi, please refer to this issue here https://github.com/wenquanlu/HandRefiner/issues/12#issuecomment-1876637894

**Comment by wenquanlu** [comment]
Also, handrefiner has been integrated into comfyui https://github.com/Fannovel16/comfyui_controlnet_aux and a1111 https://github.com/Mikubill/sd-webui-controlnet/discussions/2400, their inpainting should not have such problems.

**Comment by YouTianlong** [comment]
Thanks.
Another question, the tested images are all 512x512. Does it support images of any size?
If supported, how should I test it.
