### ISSUE TITLE
about depth map

### ISSUE THREAD

**Issue by YuehengLuo** [wenquanlu/HandRefiner#21]
I’ve noticed that the hand depth maps in the paper for RHD are different from the depth maps in the original dataset. The original dataset’s depth maps are of the whole body. How should I process them to obtain depth maps suitable for training? Could you please explain in detail the statement from the paper: ‘The segmentation maps are utilized to generate the depth and mask for the hand regions’? I would be very grateful.

**Comment by wenquanlu** [comment]
<img width="238" alt="image" src="https://github.com/wenquanlu/HandRefiner/assets/64842615/1845f67d-7d7f-45e7-97a7-e87bd0c0b494">

**Comment by YuehengLuo** [comment]
Thank you so much for your kindness and support.
