### ISSUE TITLE
安装插件后depth没有预处理器：depth_hand_refiner

### ISSUE THREAD

**Issue by Nomination-NRB** [wenquanlu/HandRefiner#24]
你好，按照教程安装后，有插件可以选择：
![image](https://github.com/wenquanlu/HandRefiner/assets/83486284/6cf8c6db-3e2d-46e8-b2e2-4b3db57f85ab)

但是在depth的controlnet中有预处理器：
![image](https://github.com/wenquanlu/HandRefiner/assets/83486284/244e0809-5f4b-4fa9-a2cd-ed30bcdbe1b5)

**Comment by wenquanlu** [comment]
Hi, 这是一个research repo，如果您想在sdwebui里用handrefiner，那可以按照这里的指示 https://github.com/Mikubill/sd-webui-controlnet/discussions/2400 ， 我因为不参与把handrefiner导入webui的编写，没法给您提供及时解答
（您可以试着升级一下webui）
您也可以在 https://github.com/Mikubill/sd-webui-controlnet里提一下这个issue，相信很快会有答复的

**Comment by Nomination-NRB** [comment]
> Hi, 这是一个research repo，如果您想在sdwebui里用handrefiner，那可以按照这里的指示 [Mikubill/sd-webui-controlnet#2400](https://github.com/Mikubill/sd-webui-controlnet/discussions/2400) ， 我因为不参与把handrefiner导入webui的编写，没法给您提供及时解答 （您可以试着更新一下webui） 您也可以在 https://github.com/Mikubill/sd-webui-controlnet 里提一下这个issue，相信很快会有答复的

好的，感谢回复，解决方法：将Controlnet升级到最新版，clone即可
