### ISSUE TITLE
 error: can't copy 'build\lib\YOGNTT.XLSX': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by toyxyz** [wenquanlu/HandRefiner#3]
When I run pip install ./manopth/., I get the following error. 

running install_lib
      error: can't copy 'build\lib\YOGNTT.XLSX': doesn't exist or not a regular file
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> manopth

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by wenquanlu** [comment]
Seems like your python version is incompatible, I am using 3.8, maybe you have newer version?

**Comment by toyxyz** [comment]
> Seems like your python version is incompatible, I am using 3.8, maybe you have newer version?

Yes. I am using 3.10.
