### ISSUE TITLE
is their docs for window ? i only see it for linux

### ISSUE THREAD

**Issue by xalteropsx** [wenquanlu/HandRefiner#33]

**Comment by wenquanlu** [comment]
Hi, this is in the end a repository for research purpose, you can install WSL in windows to run it. For better operating system compatibility, you can check out https://github.com/Fannovel16/comfyui_controlnet_aux or https://github.com/Mikubill/sd-webui-controlnet, they have HandRefiner as a functionality with thousands of other more.
