### ISSUE TITLE
unstable refined results

### ISSUE THREAD

**Issue by Aoiryo** [wenquanlu/HandRefiner#36]
Hi, thanks for your amazing works!
I am trying the model on ComfyUI, and I got the following results from different seeds.
The results seem not as good as those from the paper, what could be potential problems? Am I missing something or do you have any guesses on why this is happening?

Any suggestions would be helpful, thanks!
![截屏2024-06-27 03 07 30](https://github.com/wenquanlu/HandRefiner/assets/87690838/4112a4ca-c077-42a2-b5be-83c3b641b492)

**Comment by Aoiryo** [comment]
BTW, I am using:
materpiece, good quality, photorealistic, a Chinese woman waving her hands toward the camera
as my positive prompt, and
worst quality, bad quality, nsfw, CG,
as the negative one

**Comment by wenquanlu** [comment]
Yeah looks like definitely something is wrong, what weight are you using, and what is the control strength?

**Comment by Aoiryo** [comment]
> Thanks for your enquiry. Yeah looks like definitely something is wrong, what weight are you using, and what is the control strength? (it would be helpful if you can screenshot your entire workflow so I can try to debug)
> 
> I personally have never duplicated this project in ComfyUI, so if you try to duplicate it from scratch, it is very likely you need to overcome many bugs and issues, however, here are some existing working workflows that uses HandRefiner in ComfyUI:
> 
> * https://openart.ai/workflows/akihungac/auto-hand-refiner-workflow/gR7HQUy7NrR7NqIbEREs
> * https://civitai.com/models/257359/awesomecomfyui-auto-hand-refiner-upscale-workflow-controlnet
> * https://openart.ai/workflows/datou/hand-refiner/XNcfT4iDYnQImq2UC3lP
> * https://www.runcomfy.com/comfyui-workflows/fix-hands-with-mesh-graphormer-controlnet-in-comfyui

Thanks for your timely response!
I checked these workflows, and found that my results had weird edges cuz I didn't use 'set latent noise mask' node. Now I have the following workflow:
![截屏2024-06-27 19 16 39](https://github.com/wenquanlu/HandRefiner/assets/87690838/274abca8-1c9b-487b-876b-aac800617d71)
The hand shape is not as desired, is this because of my checkpoint or any wrong arguments?

**Comment by wenquanlu** [comment]
I am not 100% confidence of what's going on,

but from what I see from other workflows, in the "Load Checkpoint" section, they normally load a generic text-to-image weight (not an inpainting weight), so probably load this weight[https://huggingface.co/runwayml/stable-diffusion-v1-5] would work?

For example
In this link https://openart.ai/workflows/datou/hand-refiner/XNcfT4iDYnQImq2UC3lP , they load SDXLAnimeBulldozer_v10.safetensors which is a text-to-image model
In this link https://www.youtube.com/watch?v=K2uy2zcM68o , they load epicRealism.safetensors which is a text-to-image model
In this link https://civitai.com/models/257359/awesomecomfyui-auto-hand-refiner-upscale-workflow-controlnet , they load realisian_v50.safetensors, which is a text-to-image model.

Please feel free to provide further feedback

**Comment by Aoiryo** [comment]
Thanks for follow-ups!
Yes it is probably the matter of models, specifically, I switched to realisticVisionV50_v50VAE.safetensor and applied embeddings in the negative prompts, the results are pretty nice now. :)
