### ISSUE TITLE
sd-v1-5-inpainting.ckpt download link is invaild

### ISSUE THREAD

**Issue by 1851759** [wenquanlu/HandRefiner#39]
The sd-v1-5-inpainting.ckpt download link is invalid. Could you provide a new download link?Thanks a lot.

**Comment by wenquanlu** [comment]
Hi sorry for the late reply, I think you can find it in the new link here https://huggingface.co/botp/stable-diffusion-v1-5-inpainting/blob/main/sd-v1-5-inpainting.ckpt
