### ISSUE TITLE
Issue with pytorch_lightning

### ISSUE THREAD

**Issue by dayunbao** [wenquanlu/HandRefiner#5]
I just tried to run the `handrefiner.py` script after installing everything in the `requirements.txt` file, and got this error:
> ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data'

I saw a lot of people have had this error in the past.  The pytorch_lightning version in the `requirements.txt` file is pinned to 1.4.2, but the current stable version is 2.1.3.  Is there a reason for using such an old version of pytorch_lightning?

**Comment by wenquanlu** [comment]
Oh, that is because when I installed the stable diffusion https://github.com/CompVis/stable-diffusion , I use their environment.yaml which is very old... I think you can use whatever version you would like as long as there is no major conflicts...

**Comment by zhaojigang** [comment]
> I just tried to run the `handrefiner.py` script after installing everything in the `requirements.txt` file, and got this error:
> 
> > ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data'
> 
> I saw a lot of people have had this error in the past. The pytorch_lightning version in the `requirements.txt` file is pinned to 1.4.2, but the current stable version is 2.1.3. Is there a reason for using such an old version of pytorch_lightning?

hi, have you solved this problem,I also meet this error, but when I update pytorch_lightning  version to 2.1.3, I meet another error, 
```
Traceback (most recent call last):
  File "D:\ai\HandRefiner\handrefiner.py", line 39, in <module>
    from preprocessor.meshgraphormer import MeshGraphormerMediapipe
  File "D:\ai\HandRefiner\preprocessor\meshgraphormer.py", line 8, in <module>
    from MeshGraphormer.src.modeling.bert import BertConfig, Graphormer
  File "D:\ai\HandRefiner\MeshGraphormer\src\modeling\bert\__init__.py", line 3, in <module>
    from .modeling_bert import (BertConfig, BertModel,
  File "D:\ai\HandRefiner\MeshGraphormer\src\modeling\bert\modeling_bert.py", line 1
    ../../../transformers/pytorch_transformers/modeling_bert.py
    ^
SyntaxError: invalid syntax
```
